import type { Metadata } from "next";
import dynamic from "next/dynamic";

const Navbar = dynamic(() => import("@/components/Navbar"), { ssr: false });
const FooterComponent = dynamic(() => import("@/components/Footer"), {
  ssr: false,
});

export const metadata: Metadata = {
  title: "Home | Course",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <FooterComponent />
      </body>
    </html>
  );
}
